//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrador
    {
        public int ID_Administrador { get; set; }
        public string Usuario { get; set; }
        public string Contraseña { get; set; }
    }
}
